### ISSUE TITLE
Prerendering

### ISSUE THREAD

**Issue by cavis** [PRX/beta.prx.org#327]
Re-implement prerendering.

**Comment by cavis** [comment]
Notes to self:

- If really set on running phantomjs in Alpine (for prerender.io or something), you'll have to do some manual stuff [in this repo](https://github.com/fgrehm/docker-phantomjs2) and outlined in [this blog post](http://fabiorehm.com/blog/2015/07/22/building-a-minimum-viable-phantomjs-2-docker-image/).
- Zombie/JSDom install nicely - probably easier to port the old server.js or do a zombie thing like [this project](https://github.com/NathanGRomano/angular-zombie-seo/blob/master/routes/proxy.js).

**Comment by cavis** [comment]
Also, Google [deprecated their ajax-crawling scheme](https://googlewebmastercentral.blogspot.com/2015/10/deprecating-our-ajax-crawling-scheme.html) back in October.

**Comment by kookster** [comment]
Seems like a much lower priority if we don't need to worry about google at least.
There are other search engines out there. I mean, I don't use them, but they exist.

**Comment by kookster** [comment]
#208 duplicate
